---
- hosts: clearbots
  remote_user: kasutaja

  tasks:
  - name: Set up a systemd service for clearbot
    copy:
      src: resources/clearbot.service
      dest: /lib/systemd/system/clearbot.service
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Enable and start the service
    service:
      name: clearbot.service
      state: started
      enabled: yes
    become: true
