---
- hosts: clearbots
  remote_user: "{{ ansible_user }}"

  tasks:
  - name: Set up a systemd service for clearbot
    template:
      src: clearbot.service.j2
      dest: /lib/systemd/system/clearbot.service
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Enable and start the service
    service:
      name: clearbot.service
      state: started
      enabled: yes
    become: true
